# Generated by Django 6.0.7 on 2026-08-01 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_id', models.CharField(max_length=20, unique=True)),
                ('pod_name', models.CharField(max_length=100)),
                ('credit_balance', models.FloatField(default=1000.0)),
                ('escrow_balance', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_offered', models.CharField(choices=[('water', 'Water'), ('food', 'Food'), ('medicine', 'Medicine')], max_length=20)),
                ('amount_offered', models.FloatField()),
                ('price_in_credits', models.FloatField()),
                ('wanted_resource', models.CharField(blank=True, choices=[('water', 'Water'), ('food', 'Food'), ('medicine', 'Medicine')], max_length=20, null=True)),
                ('wanted_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_posted', to='core.podwallet')),
            ],
        ),
        migrations.CreateModel(
            name='TradeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('price_paid', models.FloatField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('buyer_pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.podwallet')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tradeoffer')),
                ('seller_pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.podwallet')),
            ],
        ),
    ]
